services:
  caddy:
    restart: unless-stopped
    container_name: caddy
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gnosis

networks:
  gnosis:
    external: true
